# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "My DevOps and SysAdmin Journey" # Your awesome title
email: andres.felipe.caicedo.ultengo@gmail.com
description: >
  Welcome to my DevOps and SysAdmin blog! I share my experiences and insights in streamlining projects, automating workflows,
  and delivering high-quality code. Join me on this journey as we explore the world of DevOps and System Administration.
baseurl: "" # The subpath of your site, e.g. /blog
url: "http://andrescdo.github.io" # The base hostname & protocol for your site
twitter_username: AndresCdo # Replace with your Twitter username (optional)
github_username: AndresCdo # Replace with your GitHub username (optional)

# Build settings
markdown: kramdown
